// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Project.Context;

#nullable disable

namespace Project.Migrations
{
    [DbContext(typeof(MyContext))]
    [Migration("20250912180952_InitializeV01")]
    partial class InitializeV01
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.9")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Project.Models.Category", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Categories");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Description = "Computers for work,and Gaming",
                            Name = "Labtops"
                        },
                        new
                        {
                            Id = 2,
                            Description = "Latest Android and Ios",
                            Name = "Smart Phones"
                        },
                        new
                        {
                            Id = 3,
                            Description = "Wired and wireless headphnes,AirPods",
                            Name = "HeadPhones"
                        },
                        new
                        {
                            Id = 4,
                            Description = "Digital Cameras",
                            Name = "Cameras"
                        });
                });

            modelBuilder.Entity("Project.Models.Product", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("CategoryId")
                        .HasColumnType("int");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ImagePath")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Price")
                        .HasColumnType("int");

                    b.Property<int>("Quantity")
                        .HasColumnType("int");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.HasKey("Id");

                    b.HasIndex("CategoryId");

                    b.ToTable("Products");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CategoryId = 1,
                            Description = "corei7",
                            ImagePath = "~/images/foldername",
                            Price = 30000,
                            Quantity = 5,
                            Title = "Labtop1"
                        },
                        new
                        {
                            Id = 2,
                            CategoryId = 1,
                            Description = "corei5",
                            ImagePath = "~/images/foldername",
                            Price = 15000,
                            Quantity = 3,
                            Title = "Labtop2"
                        },
                        new
                        {
                            Id = 3,
                            CategoryId = 1,
                            Description = "corei3",
                            ImagePath = "~/images/foldername",
                            Price = 10000,
                            Quantity = 2,
                            Title = "Labtop3"
                        },
                        new
                        {
                            Id = 4,
                            CategoryId = 1,
                            Description = "corei9",
                            ImagePath = "~/images/foldername",
                            Price = 50000,
                            Quantity = 10,
                            Title = "Labtop4"
                        },
                        new
                        {
                            Id = 5,
                            CategoryId = 2,
                            Description = "128GB",
                            ImagePath = "~/images/foldername",
                            Price = 4000,
                            Quantity = 15,
                            Title = "Phone1"
                        },
                        new
                        {
                            Id = 6,
                            CategoryId = 2,
                            Description = "200MP",
                            ImagePath = "~/images/foldername",
                            Price = 6000,
                            Quantity = 10,
                            Title = "Phone2"
                        },
                        new
                        {
                            Id = 7,
                            CategoryId = 3,
                            Description = "More Stable Sound",
                            ImagePath = "~/images/foldername",
                            Price = 200,
                            Quantity = 10,
                            Title = "Zuzg"
                        },
                        new
                        {
                            Id = 8,
                            CategoryId = 3,
                            Description = "Noise Canceling",
                            ImagePath = "~/images/foldername",
                            Price = 3000,
                            Quantity = 5,
                            Title = "AirPods1"
                        },
                        new
                        {
                            Id = 9,
                            CategoryId = 4,
                            Description = "Mirrorless and 32.5MP",
                            ImagePath = "~/images/foldername",
                            Price = 10000,
                            Quantity = 5,
                            Title = "Canon Eos R7"
                        },
                        new
                        {
                            Id = 10,
                            CategoryId = 4,
                            Description = "full-frame mirrorless and 33MP",
                            ImagePath = "~/images/foldername",
                            Price = 12000,
                            Quantity = 4,
                            Title = "Canon Eos R7"
                        });
                });

            modelBuilder.Entity("Project.Models.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Fname")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Lname")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Users");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Email = "user@gmail.com",
                            Fname = "Ahmed",
                            Lname = "Refaat",
                            Password = "1234"
                        },
                        new
                        {
                            Id = 2,
                            Email = "user@gmail.com",
                            Fname = "Shahd",
                            Lname = "Mohamed",
                            Password = "1234"
                        },
                        new
                        {
                            Id = 3,
                            Email = "user@gmail.com",
                            Fname = "Youssef",
                            Lname = "Abdelaziz",
                            Password = "1234"
                        },
                        new
                        {
                            Id = 4,
                            Email = "user@gmail.com",
                            Fname = "Menna",
                            Lname = "Mohamed",
                            Password = "1234"
                        },
                        new
                        {
                            Id = 5,
                            Email = "user@gmail.com",
                            Fname = "omar",
                            Lname = "Ali",
                            Password = "1234"
                        });
                });

            modelBuilder.Entity("Project.Models.Product", b =>
                {
                    b.HasOne("Project.Models.Category", "Category")
                        .WithMany("Categories")
                        .HasForeignKey("CategoryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Category");
                });

            modelBuilder.Entity("Project.Models.Category", b =>
                {
                    b.Navigation("Categories");
                });
#pragma warning restore 612, 618
        }
    }
}
